###################################################################
#  Makefile for "hello world" programs
#
#  Daniel R. Reynolds
#  SMU HPC Workshop
#  20 May 2013
###################################################################

# makefile targets
hello_cpp.exe : hello.cpp
	g++ hello.cpp -o hello_cpp.exe

hello_c.exe : hello.c
	gcc hello.c -o hello_c.exe

hello_f90.exe : hello.f90
	gfortran hello.f90 -o hello_f90.exe

hello_f77.exe : hello.f
	gfortran hello.f -o hello_f.exe



####### End of Makefile #######
